version: "3.9"
services:
  django:
    container_name: django_tasklist
    build:
      context: ./
      dockerfile: ./.docker/django/Dockerfile
    volumes:
      - .:/home/ubuntu/tasklist
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
      interval: 5s
      timeout: 5s
      retries: 5
  # https://hub.docker.com/_/nginx
  nginx:
    image: nginx:1.19
    container_name: nginx_tasklist
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./static:/var/www/static
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      django:
        condition: service_healthy
  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_tasklist
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    environment:
      MYSQL_DATABASE: 'tasklist'
      MYSQL_USER: 'tasklist'
      MYSQL_PASSWORD: 'tasklist'
      MYSQL_ROOT_PASSWORD: 'tasklist'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 1s
      timeout: 2s
      retries: 5
volumes:
  my-db:
